from pathlib import Path
import os
from ..models.models import State, GlobalImagePlan
from utils.llm_config import llm

from typing import Any
from langchain_core.messages import SystemMessage, HumanMessage
from utils.const import DECIDE_IMAGES_SYSTEM
from core.nodes.notion_publisher import publish_to_notion
from core.storage.storage import get_storage_backend, slugify
async def merge_content(state: State) -> dict[str, Any]:

    plan = state["plan"]

    ordered_sections = [md for _, md in sorted(state["sections"], key=lambda x: x[0])]
    body = "\n\n".join(ordered_sections).strip()
    merged_md = f"# {plan.blog_title}\n\n{body}\n"
    return {"merged_md": merged_md}


async def decide_images(state: State) -> dict:
    
    planner = llm.with_structured_output(GlobalImagePlan)
    merged_md = state["merged_md"]
    plan = state["plan"]
    assert plan is not None

    image_plan =  await planner.ainvoke(
        [
            SystemMessage(content=DECIDE_IMAGES_SYSTEM),
            HumanMessage(
                content=(
                    f"Blog kind: {plan.blog_kind}\n"
                    f"Topic: {state['topic']}\n\n"
                    "Insert placeholders + propose image prompts.\n\n"
                    f"{merged_md}"
                )
            ),
        ]
    )

    return {
        "md_with_placeholders": image_plan.md_with_placeholders,
        "image_specs": [img.model_dump() for img in image_plan.images],
    }


async def generate_and_place_images(state: State) -> dict[str, Any]:
    plan = state["plan"]
    assert plan is not None

    storage = get_storage_backend()

    md = state.get("md_with_placeholders") or state["merged_md"]
    image_specs = state.get("image_specs") or []
    print("Reducer started")

    for spec in image_specs:
        placeholder  = spec["placeholder"]         
        raw_filename = spec["filename"]              
      
        stem, _, ext = raw_filename.rpartition(".")
        safe_name    = f"{slugify(stem)}.{ext or 'png'}"
        blob_name    = f"images/{safe_name}"

        already_uploaded = await storage.exists(blob_name)

        if not already_uploaded:
            try:
                img_bytes = await _gemini_generate_image_bytes(spec["prompt"])
                image_url = await storage.upload_image(
                    filename=safe_name,
                    data=img_bytes,
                    content_type="image/png",
                )
                print("Image generated")
            except Exception as exc:
                
                fallback = (
                    f"> **[IMAGE GENERATION FAILED]** {spec.get('caption', '')}\n"
                    f">\n"
                    f"> **Alt:** {spec.get('alt', '')}\n"
                    f"> **Prompt:** {spec.get('prompt', '')}\n"
                    f"> **Error:** {exc}\n"
                )
                md = md.replace(placeholder, fallback)
                continue
        else:
            image_url = await storage.public_url(blob_name)

    
        img_md = f"![{spec['alt']}]({image_url})\n*{spec['caption']}*"
        md = md.replace(placeholder, img_md)


    print("Image loop done, starting markdown upload")
    safe_title   = slugify(plan.blog_title)
    md_filename  = f"{safe_title}.md"
    print(f"Uploading markdown: {md_filename}, size: {len(md)} chars")
    blog_url = await storage.upload_markdown(
        filename=md_filename,
        content=md,
    )
    print("Publishing to Notion...")
    notion_url = await publish_to_notion(
        title=plan.blog_title,
        markdown=md
    )
    print(f"Notion upload complete : {notion_url}")
    return {
        "final": md,           
        "final_blog_url": blog_url,  
        "notion_url" : notion_url
    }



async def _gemini_generate_image_bytes(prompt: str) -> bytes:
    """
    Returns raw image bytes generated by Gemini.
    Requires: pip install google-genai
    Env var: GOOGLE_API_KEY
    """
    from google import genai
    from google.genai import types

    api_key = os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        raise RuntimeError("GOOGLE_API_KEY is not set.")

    client = genai.Client(api_key=api_key)

    resp = await client.aio.models.generate_content(
        model="gemini-2.5-flash-image",
        contents=prompt,
        config=types.GenerateContentConfig(
            response_modalities=["IMAGE"],
            safety_settings=[
                types.SafetySetting(
                    category="HARM_CATEGORY_DANGEROUS_CONTENT",
                    threshold="BLOCK_ONLY_HIGH",
                )
            ],
        ),
    )

    
    parts = getattr(resp, "parts", None)
    if not parts and getattr(resp, "candidates", None):
        try:
            parts = resp.candidates[0].content.parts
        except Exception:
            parts = None

    if not parts:
        raise RuntimeError("No image content returned (safety/quota/SDK change).")

    for part in parts:
        inline = getattr(part, "inline_data", None)
        if inline and getattr(inline, "data", None):
            return inline.data

    raise RuntimeError("No inline image bytes found in response.")


# async def generate_and_place_images(state: State) -> dict:

#     plan = state["plan"]
#     assert plan is not None

#     md = state.get("md_with_placeholders") or state["merged_md"]
#     image_specs = state.get("image_specs", []) or []


#     if not image_specs:
#         filename = f"{plan.blog_title}.md"
#         Path(filename).write_text(md, encoding="utf-8")
#         return {"final": md}

#     images_dir = Path("images")
#     images_dir.mkdir(exist_ok=True)

#     for spec in image_specs:
#         placeholder = spec["placeholder"]
#         filename = spec["filename"]
#         out_path = images_dir / filename

#         #
#         if not out_path.exists():
#             try:
#                 img_bytes = await _gemini_generate_image_bytes(spec["prompt"])
#                 out_path.write_bytes(img_bytes)
#             except Exception as e:
                
#                 prompt_block = (
#                     f"> **[IMAGE GENERATION FAILED]** {spec.get('caption','')}\n>\n"
#                     f"> **Alt:** {spec.get('alt','')}\n>\n"
#                     f"> **Prompt:** {spec.get('prompt','')}\n>\n"
#                     f"> **Error:** {e}\n"
#                 )
#                 md = md.replace(placeholder, prompt_block)
#                 continue

#         img_md = f"![{spec['alt']}](images/{filename})\n*{spec['caption']}*"
#         md = md.replace(placeholder, img_md)

#     filename = f"{plan.blog_title}.md"
#     Path(filename).write_text(md, encoding="utf-8")
#     return {"final": md}